// OutDoor Data

plantsData = [
  {
    id: 1,
    name: "Lime",
    species: "Citrus aurantiifolia",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "South Asia",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Lime is a small, green citrus fruit known for its tangy, acidic flavor. It's commonly used in cooking, beverages, and as a garnish. The plant is adapted to full sun and well-draining soil.",
    image: ["./img/lime.png", "./img/lime1.png", "./img/lime2.png"],
    price: "6,150",
  },
  {
    id: 2,
    name: "Orange",
    species: "Citrus sinensis",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate to Fast",
    origin: "Southeast Asia",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Orange is a popular citrus fruit known for its sweet and tangy flavor. It is widely consumed fresh or as juice. The orange tree requires full sun and well-draining soil to thrive.",
    image: ["./img/orange.png", "./img/orange2.png", "./img/orange1.png"],
    price: "4,480",
  },
  {
    id: 3,
    name: "Grapefruit",
    species: "Citrus paradisi",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Barbados",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Grapefruit is a citrus fruit known for its tangy, slightly bitter flavor and high vitamin C content. It grows best in full sun and requires well-draining soil.",
    image: [
      "./img/Grapefruit.png",
      "./img/Grapefruit1.png",
      "./img/Grapefruit2.png",
    ],
    price: "4,000",
  },
  {
    id: 4,
    name: "Mandarin Oranges",
    species: "Citrus reticulata",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "China",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Mandarin is a small, sweet citrus fruit known for its easy-to-peel skin and juicy segments. It thrives in full sun and well-draining soil.",
    image: ["./img/Mandarin.png", "./img/Mandarin1.png", "./img/Mandarin2.png"],
    price: "4,000",
  },
  {
    id: 5,
    name: "Tangerine",
    species: "Citrus tangerina",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Japan",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Tangerine is a small citrus fruit known for its bright orange color and sweet, tangy flavor. It is easy to peel and segments are juicy. The plant prefers full sun and well-draining soil.",
    image: [
      "./img/Tangerine.png",
      "./img/Tangerine1.png",
      "./img/Tangerine2.png",
    ],
    price: "4,410",
  },
  {
    id: 6,
    name: "Pomelo",
    species: "Citrus maxima",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Slow to Moderate",
    origin: "Southeast Asia",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Pomelo is the largest citrus fruit known for its thick, green or yellow skin and sweet, mildly tangy flesh. It grows best in full sun and well-draining soil.",
    image: ["./img/Pomelo.png", "./img/Pomelo1.png", "./img/Pomelo2.png"],
    price: "3,390",
  },
  {
    id: 7,
    name: "Bergamot Orange",
    species: "Citrus bergamia",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Slow to Moderate",
    origin: "Italy",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Bergamot orange is a citrus fruit known for its distinct, aromatic flavor and essential oils used in perfumes and Earl Grey tea. It requires full sun and well-draining soil to thrive.",
    image: ["./img/Bergamot.png", "./img/Bergamot1.png", "./img/Pomelo2.png"],
    price: "4,100",
  },
  {
    id: 8,
    name: "Kumquat",
    species: "Fortunella margarita",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Slow to Moderate",
    origin: "China",
    generation: "Genus: Fortunella, Family: Rutaceae",
    description:
      "Kumquat is a small citrus fruit known for its sweet and tangy flavor, and edible skin. It thrives in full sun and well-draining soil.",
    image: ["./img/Kumquat.png", "./img/Kumquat1.png", "./img/Kumquat2.png"],
    price: "7,500",
  },
  {
    id: 9,
    name: "Citron",
    species: "Citrus medica",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Slow to Moderate",
    origin: "India and China",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Citron is a large, yellow citrus fruit with a thick, rough skin and a lemon-like aroma. It is often used in preserves and as a flavoring. The plant requires full sun and well-draining soil.",
    image: ["./img/Citron.png", "./img/Citron1.png", "./img/Citron2.png"],
    price: "2,000",
  },
  {
    id: 10,
    name: "Bitter Orange",
    species: "Citrus aurantium",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Southeast Asia",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Bitter orange is a citrus fruit known for its sharp, tangy flavor and bitter taste. It is used in marmalade, liqueurs, and traditional medicine. The plant thrives in full sun and well-draining soil.",
    image: ["./img/Bitter.png", "./img/Bitter1.png", "./img/bitter2.png"],
    price: "4,410",
  },
  {
    id: 11,
    name: "Calamondin",
    species: "Citrus microcarpa",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Philippines",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Calamondin is a small citrus fruit with a tart flavor and thin, orange skin. It is often used in Filipino cuisine and as a decorative plant. It grows best in full sun and well-draining soil.",
    image: [
      "./img/Calamondin.png",
      "./img/Calamondin1.png",
      "./img/Calamondin2.png",
    ],
    price: "4,830",
  },
  {
    id: 12,
    name: "Kaffir Lime",
    species: "Citrus hystrix",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Southeast Asia",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Kaffir lime is known for its aromatic leaves and distinct, bumpy fruit. The zest and leaves are commonly used in Southeast Asian cuisine for their unique flavor. The plant prefers full sun and well-draining soil.",
    image: ["./img/Kaffir.png", "./img/Kaffir1.png", "./img/Kaffir2.png"],
    price: "2,000",
  },
  {
    id: 13,
    name: "Yuzu",
    species: "Citrus junos",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Slow to Moderate",
    origin: "East Asia",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Yuzu is a citrus fruit with a distinct tart and aromatic flavor, often used in Japanese cuisine and as a flavoring in various dishes and beverages. The plant thrives in full sun and well-draining soil.",
    image: ["./img/Yuzu.png", "./img/Yuzu1.png", "./img/Yuzu2.png"],
    price: "7,000",
  },
  {
    id: 14,
    name: "Sudachi",
    species: "Citrus sudachi",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Slow to Moderate",
    origin: "Japan",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Sudachi is a small, green citrus fruit known for its tart flavor and aromatic zest. It is often used in Japanese cuisine, particularly in sauces and dressings. The plant grows best in full sun and well-draining soil.",
    image: ["./img/Sudachi.png", "./img/Sudachi1.png", "./img/Sudachi2.png"],
    price: "22,500",
  },
  {
    id: 15,
    name: "Kinkan",
    species: "Fortunella japonica",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Slow to Moderate",
    origin: "Japan",
    generation: "Genus: Fortunella, Family: Rutaceae",
    description:
      "Kinkan, also known as kumquat, is a small citrus fruit with a sweet and tangy flavor. The fruit's skin is edible and contributes to its unique taste. It prefers full sun and well-draining soil.",
    image: ["./img/Kumquat.png", "./img/Kumquat1.png", "./img/Kumquat2.png"],
    price: "2,500",
  },
  {
    id: 16,
    name: "Clementine",
    species: "Citrus clementina",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Algeria",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Clementine is a small, sweet citrus fruit known for its easy-to-peel skin and juicy segments. It is often enjoyed fresh or as a snack. The plant thrives in full sun and well-draining soil.",
    image: [
      "./img/Clementine.png",
      "./img/Clementine1.png",
      "./img/Clementine2.png",
    ],
    price: "7,500",
  },
  {
    id: 17,
    name: "Seville Orange",
    species: "Citrus aurantium",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Spain",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Seville orange, also known as bitter orange, is renowned for its tart flavor and is commonly used in marmalade and as a flavoring. It prefers full sun and well-draining soil.",
    image: ["./img/Bitter.png", "./img/Bitter1.png", "./img/bitter2.png"],
    price: "4,410",
  },
  {
    id: 18,
    name: "Mandarins",
    species: "Citrus reticulata",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "China",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Mandarins are small, sweet citrus fruits known for their easy-to-peel skin and juicy segments. They are often enjoyed fresh or used in cooking and desserts. The plant thrives in full sun and well-draining soil.",
    image: ["./img/Mandarin.png", "./img/Mandarin1.png", "./img/Mandarin2.png"],
    price: "4,000",
  },
  {
    id: 19,
    name: "Finger Lime",
    species: "Citrus australasica",
    type: "Citrus Fruit",
    category: "Fruit",
    main: "limeData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Slow to Moderate",
    origin: "Australia",
    generation: "Genus: Citrus, Family: Rutaceae",
    description:
      "Finger lime is a unique citrus fruit known for its elongated shape and caviar-like vesicles that burst with tangy juice. It is used in gourmet dishes and as a garnish. The plant thrives in full sun and well-draining soil.",
    image: ["./img/Finger.png", "./img/Finger1.png", "./img/Finger2.png"],
    price: "5,000",
  },

  {
    id: 51,
    name: "Sindhri Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Pakistan",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Sindhri mango is celebrated for its large size, sweet flavor, and juicy, fiberless flesh. It has a golden-yellow skin when ripe and is highly valued for its aromatic and rich taste. The plant thrives in full sun and well-draining soil.",
    image: ["./img/Sindhri.png", "./img/Sindhri1.png", "./img/Sindhri2.png"],
    price: "4,400",
  },
  {
    id: 52,
    name: "Chaunsa Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Chaunsa mango is highly prized for its exceptionally sweet, rich flavor and smooth, juicy texture. It has a golden-yellow skin with a slight blush when ripe and is considered one of the best mango varieties. The plant requires full sun and well-draining soil to thrive.",
    image: ["./img/Chaunsa.png", "./img/Chaunsa1.png", "./img/Chaunsa2.png"],
    price: "7,000",
  },
  {
    id: 53,
    name: "Langra Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Langra mango is known for its distinctive flavor and smooth, fiberless texture. It has a green skin that turns yellow when ripe and is highly valued for its sweet, tangy taste. The plant thrives in full sun and well-draining soil.",
    image: ["./img/Langra.png", "./img/Langra1.png", "./img/Langra2.png"],
    price: "7,000",
  },
  {
    id: 54,
    name: "Dusheri Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Dusheri mango is celebrated for its sweet, tangy flavor and rich, creamy texture. It has a vibrant yellow skin with a hint of red when ripe and is highly valued for its aromatic taste. The plant thrives in full sun and well-draining soil.",
    image: ["./img/Dusheri.png", "./img/Chaunsa1.png", "./img/Chaunsa2.png"],
    price: "6,000",
  },
  {
    id: 55,
    name: "Anwar Ratol Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Pakistan",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Anwar Ratol mango is known for its small size, exceptional sweetness, and aromatic flavor. It has a yellow skin when ripe and is highly prized for its rich taste and minimal fiber. The plant thrives in full sun and well-draining soil.",
    image: ["./img/Anwar.png", "./img/Anwar1.png", "./img/Anwar2.png"],
    price: "6,500",
  },
  {
    id: 56,
    name: "Sindhri Chaunsa Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Pakistan/India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Sindhri Chaunsa mango combines the sweetness and rich flavor of Chaunsa with the large size and juicy texture of Sindhri. It has a golden-yellow skin and is highly prized for its aromatic, fiberless flesh. The plant requires full sun and well-draining soil to thrive.",
    image: ["./img/SindhriC.png", "./img/SindhriC1.png", "./img/SindhriC2.png"],
    price: "6,500",
  },
  {
    id: 57,
    name: "White Chaunsa Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Pakistan/India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "White Chaunsa mango is a variant of the Chaunsa mango, known for its distinctive creamy, pale yellow flesh. It has a sweet, rich flavor with minimal fiber and is highly valued for its smooth, juicy texture. The plant thrives in full sun and well-draining soil.",
    image: ["./img/WhiteC.png", "./img/WhiteC1.png", "./img/WhiteC2.png"],
    price: "6,500",
  },
  {
    id: 58,
    name: "Kesar Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Kesar mango, also known as 'Saffron Mango,' is famous for its vibrant orange color, sweet flavor, and rich, creamy texture. It is highly prized in India for its aromatic taste and juicy flesh. The plant thrives in full sun and well-draining soil.",
    image: ["./img/Kesar.png", "./img/Kesar1.png", "./img/Kesar2.png"],
    price: "6,500",
  },
  {
    id: 59,
    name: "Banganapalli Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Banganapalli mango, also known as 'Banana Mango,' is renowned for its large size, sweet flavor, and smooth, fiberless flesh. It has a golden-yellow skin when ripe and is valued for its juicy, aromatic taste. The plant prefers full sun and well-draining soil.",
    image: [
      "./img/Banganapalli.png",
      "./img/Banganapalli1.png",
      "./img/Banganapalli2.png",
    ],
    price: "7,900",
  },
  {
    id: 60,
    name: "Dusheri Chaunsa Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Pakistan/India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Dusheri Chaunsa mango is a delightful combination of the sweet, tangy flavor of Dusheri with the rich, creamy texture of Chaunsa. It has a vibrant yellow skin with a hint of red when ripe and is highly valued for its aromatic, fiberless flesh. The plant thrives in full sun and well-draining soil.",
    image: ["./img/Dusheri.png", "./img/Dusheri1.png", "./img/Chaunsa2.png"],
    price: "6,000",
  },
  {
    id: 61,
    name: "Langra Chaunsa Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Pakistan/India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Langra Chaunsa mango combines the unique tanginess of Langra with the rich sweetness of Chaunsa. It features a greenish-yellow skin and a smooth, fiberless texture. This mango variety is highly valued for its aromatic flavor and juicy flesh. The plant requires full sun and well-draining soil to thrive.",
    image: ["./img/LangraC.png", "./img/Langra1.png", "./img/Langra2.png"],
    price: "7,000",
  },
  {
    id: 62,
    name: "Banganapalli Chaunsa Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Pakistan/India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Banganapalli Chaunsa mango is a hybrid variety that combines the large size and sweetness of Banganapalli with the rich, creamy texture of Chaunsa. It features a golden-yellow skin with a smooth, fiberless texture and is prized for its aromatic flavor. The plant thrives in full sun and well-draining soil.",
    image: [
      "./img/Banganapalli.png",
      "./img/Banganapalli1.png",
      "./img/Banganapalli2.png",
    ],
    price: "7,900",
  },
  {
    id: 63,
    name: "Himsagar Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Himsagar mango is known for its small size, exceptional sweetness, and aromatic flavor. It has a smooth, fiberless texture and a golden-yellow skin when ripe. This variety is highly prized for its rich taste and minimal fiber. The plant prefers full sun and well-draining soil.",
    image: ["./img/Himsagar.png", "./img/Himsagar1.png", "./img/Himsagar2.png"],
    price: "9,900",
  },
  {
    id: 64,
    name: "Neelum Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "India/Pakistan",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Neelum mango is renowned for its bright yellow skin and sweet, tangy flavor. It has a smooth, fiberless texture and is highly valued for its juicy and aromatic flesh. The plant thrives in full sun and well-draining soil.",
    image: ["./img/Neelum.png", "./img/Neelum1.png", "./img/Neelum2.png"],
    price: "5,000",
  },
  {
    id: 65,
    name: "Fajri",
    species: "Mangifera indica",
    type: "Fruit Tree",
    category: "Edible Plant",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining, Sandy loam",
    growthRate: "Fast",
    origin: "India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Fajri is a popular mango variety known for its large, elongated fruits with a sweet and rich flavor. It is often enjoyed during the peak mango season in India. The tree thrives in tropical climates and requires full sun for optimal fruit production.",
    image: ["./img/Fajri.png", "./img/Fajri1.png", "./img/Fajri2.png"],
    price: "5,000",
  },
  {
    id: 66,
    name: "Mulgoba Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Mulgoba mango is renowned for its rich, sweet flavor and smooth, fiberless texture. It has a golden-yellow skin when ripe and is highly prized for its juicy, aromatic flesh. The plant thrives in full sun and well-draining soil.",
    image: ["./img/Mulgoba.png", "./img/Mulgoba1.png", "./img/Mulgoba2.png"],
    price: "7,000",
  },
  {
    id: 67,
    name: "Almas",
    species: "Mangifera indica",
    type: "Fruit Tree",
    category: "Edible Plant",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate",
    origin: "India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Almas is a premium variety of mango known for its smooth, golden skin and rich, sweet taste. This variety is often sought after for its exceptional flavor and is a favorite in many regions of India. It thrives in warm, sunny climates with well-draining soil.",
    image: ["./img/Almas.png", "./img/Almas1.png", "./img/Almas2.png"],
    price: "7,000",
  },
  {
    id: 68,
    name: "Raspuri Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Raspuri mango is recognized for its small size and intense sweetness. It has a smooth, fiberless texture and a golden-yellow skin when ripe. The mango is highly valued for its rich, aromatic flavor and is often used in desserts and beverages. The plant thrives in full sun and well-draining soil.",
    image: ["./img/Raspuri.png", "./img/Raspuri1.png", "./img/Raspuri2.png"],
    price: "7,000",
  },
  {
    id: 69,
    name: "Mango Pak",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Pakistan",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Mango Pak is known for its sweet, aromatic flavor and smooth, fiberless texture. It features a vibrant yellow skin when ripe and is highly prized for its rich taste and juiciness. The plant requires full sun and well-draining soil for optimal growth.",
    image: ["./img/Mango.png", "./img/Mango1.png", "./img/Mango2.png"],
    price: "8,000",
  },
  {
    id: 70,
    name: "Krishna Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Krishna mango is celebrated for its distinct flavor and smooth, fiberless texture. It has a golden-yellow skin and is known for its sweet, aromatic taste. This variety is highly valued for its rich flavor and juicy flesh. The plant thrives in full sun and well-draining soil.",
    image: ["./img/Krishna.png", "./img/Krishna1.png", "./img/Krishna2.png"],
    price: "8,000",
  },
  {
    id: 71,
    name: "Hari Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Hari mango is known for its rich, sweet flavor and smooth, fiberless texture. It has a distinctive yellow-green skin when ripe and is highly valued for its juicy, aromatic flesh. The plant requires full sun and well-draining soil for optimal growth.",
    image: ["./img/Hari.png", "./img/Hari1.png", "./img/Hari2.png"],
    price: "6,000",
  },
  {
    id: 72,
    name: "Sundari Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Sundari mango is known for its unique sweet flavor and smooth, fiberless texture. It has a vibrant yellow skin when ripe and is appreciated for its juicy, aromatic flesh. The plant thrives in full sun and well-draining soil.",
    image: ["./img/Sundari.png", "./img/Sundari1.png", "./img/Sundari2.png"],
    price: "5,500",
  },
  {
    id: 73,
    name: "Aamrapali Mango",
    species: "Mangifera indica",
    type: "Fruit",
    category: "Tropical Fruit",
    main: "mangoData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "India",
    generation: "Genus: Mangifera, Family: Anacardiaceae",
    description:
      "Aamrapali mango, also known as 'Amrapali,' is renowned for its exceptionally sweet flavor and smooth, fiberless texture. It features a vibrant orange skin and is highly valued for its juicy, aromatic flesh. The plant requires full sun and well-draining soil to thrive.",
    image: [
      "./img/Aamrapali.png",
      "./img/Aamrapali1.png",
      "./img/Aamrapali2.png",
    ],
    price: "7,500",
  },

  // Indoor Data

  {
    id: 101,
    name: "Rubber Plant",
    species: "Ficus elastica",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Indirect Sunlight",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate",
    origin: "Southeast Asia",
    generation: "Genus: Ficus, Family: Moraceae",
    description:
      "The Rubber Plant is a popular indoor plant known for its large, glossy leaves. It is easy to care for and can thrive in indirect sunlight with moderate watering. The plant adds a tropical touch to any indoor space.",
    image: ["./img/297.png", "./img/298.png", "./img/299.png"],
    price: "850",
  },
  {
    id: 102,
    name: "Fiddle Leaf Fig",
    species: "Ficus lyrata",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate to Fast",
    origin: "Western Africa",
    generation: "Genus: Ficus, Family: Moraceae",
    description:
      "The Fiddle Leaf Fig is a trendy indoor plant known for its large, violin-shaped leaves. It thrives in bright, indirect light and requires regular watering, making it a favorite for adding a dramatic, tropical vibe to interior spaces.",
    image: ["./img/300.png", "./img/301.png", "./img/302.png"],
    price: "2,500",
  },
  {
    id: 103,
    name: "Weeping Fig",
    species: "Ficus benjamina",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate",
    origin: "Southeast Asia and Northern Australia",
    generation: "Genus: Ficus, Family: Moraceae",
    description:
      "The Weeping Fig is a popular indoor plant known for its graceful, arching branches and glossy, teardrop-shaped leaves. It thrives in bright, indirect light and needs moderate watering. It’s ideal for adding a touch of elegance to indoor spaces.",
    image: ["./img/303.png", "./img/304.png", "./img/305.png"],
    price: "1,2,750",
  },
  {
    id: 104,
    name: "Chinese Banyan",
    species: "Ficus microcarpa",
    type: "Indoor/Outdoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light to Full Sun",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Fast",
    origin: "Southeast Asia",
    generation: "Genus: Ficus, Family: Moraceae",
    description:
      "The Chinese Banyan is a versatile plant, often grown as a bonsai, known for its dense foliage and aerial roots. It thrives in both indoor and outdoor environments, requiring bright indirect light to full sun and moderate watering.",
    image: ["./img/306.png", "./img/307.png", "./img/308.png"],
    price: "2,350",
  },
  {
    id: 105,
    name: "Creeping Fig",
    species: "Ficus pumila",
    type: "Climbing/Trailing Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light to Partial Shade",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Fast",
    origin: "East Asia",
    generation: "Genus: Ficus, Family: Moraceae",
    description:
      "The Creeping Fig is a fast-growing climbing plant known for its small, heart-shaped leaves. It is often used as a ground cover or to cover walls and trellises, thriving in bright indirect light to partial shade with moderate watering.",
    image: ["./img/309.png", "./img/310.png", "./img/311.png"],
    price: "150",
  },
  {
    id: 106,
    name: "Alii Fig",
    species: "Ficus binnendijkii",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate",
    origin: "Southeast Asia",
    generation: "Genus: Ficus, Family: Moraceae",
    description:
      "The Alii Fig is a popular indoor plant with long, narrow leaves that add a tropical touch to any space. It thrives in bright indirect light and requires moderate watering, making it a low-maintenance choice for home or office environments.",
    image: ["./img/312.png", "./img/313.png", "./img/314.png"],
    price: "6,750",
  },
  {
    id: 107,
    name: "Indian Laurel",
    species: "Ficus retusa",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate",
    origin: "Southeast Asia",
    generation: "Genus: Ficus, Family: Moraceae",
    description:
      "The Indian Laurel is a versatile indoor plant known for its glossy, dark green leaves and compact growth. It thrives in bright indirect light and requires moderate watering, making it a popular choice for indoor spaces and bonsai cultivation.",
    image: ["./img/315.png", "./img/316.png", "./img/317.png"],
    price: "9,000",
  },
  {
    id: 108,
    name: "Peepal Tree (Bonsai Form)",
    species: "Ficus religiosa",
    type: "Bonsai",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Slow",
    origin: "India, Southeast Asia",
    generation: "Genus: Ficus, Family: Moraceae",
    description:
      "The Peepal Tree, when cultivated as a bonsai, features heart-shaped leaves and a distinctive trunk. This bonsai variety is revered for its spiritual significance and decorative appeal. It thrives in bright indirect light and requires moderate watering.",
    image: ["./img/318.png", "./img/319.png", "./img/320.png"],
    price: "300",
  },
  {
    id: 109,
    name: "Banana Leaf Fig",
    species: "Ficus maclellandii",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate",
    origin: "Southeast Asia",
    generation: "Genus: Ficus, Family: Moraceae",
    description:
      "The Banana Leaf Fig is known for its large, elongated leaves that resemble banana leaves. It is a popular indoor plant due to its attractive foliage and adaptability to indoor conditions. It thrives in bright indirect light and requires moderate watering.",
    image: ["./img/321.png", "./img/322.png", "./img/323.png"],
    price: "2,599",
  },
  {
    id: 110,
    name: "Mistletoe Fig",
    species: "Ficus deltoidea",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Slow to Moderate",
    origin: "Southeast Asia",
    generation: "Genus: Ficus, Family: Moraceae",
    description:
      "The Mistletoe Fig is an attractive indoor plant known for its small, rounded leaves and compact growth habit. It is popular for its ability to adapt to indoor conditions and is ideal for smaller spaces. It thrives in bright indirect light and needs moderate watering.",
    image: ["./img/324.png", "./img/325.png", "./img/326.png"],
    price: "6,150",
  },
  {
    id: 111,
    name: "Dragon Tree",
    species: "Dracaena marginata",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Low to Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Slow to Moderate",
    origin: "Madagascar",
    generation: "Genus: Dracaena, Family: Asparagaceae",
    description:
      "The Dragon Tree is known for its slender trunk and long, narrow leaves with red edges. It is a popular indoor plant due to its low maintenance requirements and ability to thrive in a variety of indoor conditions. It prefers bright indirect light and has modest water needs.",
    image: ["./img/327.png", "./img/328.png", "./img/329.png"],
    price: "2,340",
  },
  {
    id: 112,
    name: "Corn Plant",
    species: "Dracaena fragrans",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate",
    origin: "Tropical Africa",
    generation: "Genus: Dracaena, Family: Asparagaceae",
    description:
      "The Corn Plant is a popular indoor plant known for its glossy, lance-shaped leaves and tall, elegant form. It thrives in bright indirect light and requires moderate watering. It’s well-suited for adding a touch of greenery to home or office environments.",
    image: ["./img/330.png", "./img/331.png", "./img/332.png"],
    price: "1,300",
  },
  {
    id: 113,
    name: "Lucky Bamboo",
    species: "Dracaena sanderiana",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Low to Moderate",
    soil: "Hydroponic or Well-draining",
    growthRate: "Slow to Moderate",
    origin: "Central Africa",
    generation: "Genus: Dracaena, Family: Asparagaceae",
    description:
      "Lucky Bamboo is a popular indoor plant known for its resilience and elegant appearance. Despite its name, it's not a true bamboo but a member of the Dracaena genus. It grows well in water or soil and thrives in bright indirect light. It's often used as a symbol of good fortune and prosperity.",
    image: ["./img/333.png", "./img/334.png", "./img/335.png"],
    price: "5,000",
  },
  {
    id: 114,
    name: "Song of India",
    species: "Dracaena reflexa",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate",
    origin: "Madagascar, Southeast Asia",
    generation: "Genus: Dracaena, Family: Asparagaceae",
    description:
      "The Song of India is known for its striking, variegated leaves that are green with yellow or cream stripes. It’s a versatile indoor plant that adds a tropical touch to any space. It thrives in bright indirect light and requires moderate watering.",
    image: ["./img/336.png", "./img/337.png", "./img/338.png"],
    price: "350",
  },
  {
    id: 115,
    name: "Janet Craig",
    species: "Dracaena deremensis",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Slow to Moderate",
    origin: "Tropical Africa",
    generation: "Genus: Dracaena, Family: Asparagaceae",
    description:
      "The Janet Craig is a hardy indoor plant known for its dark green, glossy leaves. It’s popular for its ability to tolerate low light and irregular watering. It thrives in bright indirect light and requires moderate watering, making it an excellent choice for indoor spaces.",
    image: ["./img/339.png", "./img/340.png", "./img/341.png"],
    price: "6,950",
  },
  {
    id: 116,
    name: "Compact Janet Craig",
    species: "Dracaena compacta",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Slow",
    origin: "Tropical Africa",
    generation: "Genus: Dracaena, Family: Asparagaceae",
    description:
      "The Compact Janet Craig is a smaller, more compact version of the Janet Craig Dracaena. It features the same dark green, glossy leaves but in a more compact form, making it ideal for smaller spaces. It thrives in bright indirect light and requires moderate watering.",
    image: ["./img/342.png", "./img/343.png", "./img/344.png"],
    price: "4,250",
  },
  {
    id: 117,
    name: "Striped Dracaena",
    species: "Dracaena warneckii",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Slow to Moderate",
    origin: "Tropical Africa",
    generation: "Genus: Dracaena, Family: Asparagaceae",
    description:
      "The Striped Dracaena is known for its striking, variegated leaves that have alternating green and white or cream stripes. It’s a popular indoor plant due to its unique appearance and adaptability to indoor conditions. It thrives in bright indirect light and requires moderate watering.",
    image: ["./img/345.png", "./img/346.png", "./img/347.png"],
    price: "2,340",
  },
  {
    id: 118,
    name: "Mass Cane",
    species: "Dracaena massangeana",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate",
    origin: "Tropical Africa",
    generation: "Genus: Dracaena, Family: Asparagaceae",
    description:
      "The Mass Cane, also known as Corn Plant, is recognized for its tall, cane-like stems and rosettes of wide, glossy leaves. It’s a popular choice for indoor environments due to its striking appearance and ease of care. It thrives in bright indirect light and requires moderate watering.",
    image: ["./img/348.png", "./img/349.png", "./img/350.png"],
    price: "2,500",
  },
  {
    id: 119,
    name: "Lemon Lime Dracaena",
    species: "Dracaena lemon lime",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate",
    origin: "Tropical Africa",
    generation: "Genus: Dracaena, Family: Asparagaceae",
    description:
      "The Lemon Lime Dracaena is known for its vibrant, bright green and yellow striped foliage, which adds a lively touch to any indoor space. It thrives in bright indirect light and has moderate watering needs, making it a popular choice for home and office decor.",
    image: ["./img/351.png", "./img/352.png", "./img/353.png"],
    price: "400",
  },
  {
    id: 120,
    name: "Variegated Dragon Tree",
    species: "Dracaena steudneri",
    type: "Indoor Plant",
    category: "Decorative Plant",
    main: "IndoorData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Slow to Moderate",
    origin: "Madagascar",
    generation: "Genus: Dracaena, Family: Asparagaceae",
    description:
      "The Variegated Dragon Tree is known for its striking, variegated leaves with green and cream or yellow stripes. It is a hardy indoor plant that adds a dramatic touch to any space. It thrives in bright indirect light and requires moderate watering.",
    image: ["./img/354.png", "./img/355.png", "./img/356.png"],
    price: "2,340",
  },

  // Succulents Data
  {
    id: 151,
    name: "Aloe Vera",
    species: "Aloe barbadensis miller",
    type: "Succulent",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Full Sun",
    water: "Low",
    soil: "Sandy",
    growthRate: "Slow",
    origin: "Arabian Peninsula",
    generation: "Genus: Aloe, Family: Asphodelaceae",
    description:
      "Aloe Vera is known for its medicinal properties, particularly in treating skin conditions. It's a hardy succulent that thrives in dry, sunny environments.",
    image: ["./img/1.png", "./img/2.png", "./img/3.png"],
    price: "490",
  },
  {
    id: 152,
    name: "Aloe perfoliata",
    species: "Aloe perfoliata",
    type: "Succulent",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Slow",
    origin: "South Africa",
    generation: "Genus: Aloe, Family: Asphodelaceae",
    description:
      "Aloe perfoliata is a distinctive succulent known for its rosette of fleshy, triangular leaves that often have a subtle, colorful tint. It prefers bright indirect light and requires moderate watering. This plant adds a unique touch to succulent collections and indoor gardens.",
    image: ["./img/4.png", "./img/5.png", "./img/6.png"],
    price: "2500",
  },
  {
    id: 153,
    name: "Aloe brevifolia",
    species: "Aloe brevifolia",
    type: "Succulent",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Slow",
    origin: "South Africa",
    generation: "Genus: Aloe, Family: Asphodelaceae",
    description:
      "Aloe brevifolia, also known as Short-Leaf Aloe, is a compact succulent with short, triangular leaves that form rosettes. It has a distinctive appearance and is well-suited for indoor environments. The plant thrives in bright indirect light and requires moderate watering.",
    image: ["./img/7.png", "./img/8.png", "./img/9.png"],
    price: "4700",
  },
  {
    id: 154,
    name: "Aloe maculata",
    species: "Aloe maculata",
    type: "Succulent",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "South Africa",
    generation: "Genus: Aloe, Family: Asphodelaceae",
    description:
      "Aloe maculata, commonly known as Soap Aloe, features spotted leaves with a distinctive pattern that makes it a popular choice for ornamental plantings. It prefers bright indirect light and requires moderate watering. This plant is known for its unique appearance and low maintenance needs.",
    image: ["./img/10.png", "./img/11.png", "./img/12.png"],
    price: "2500",
  },
  {
    id: 155,
    name: "Aloe aristata",
    species: "Aloe aristata",
    type: "Succulent",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Slow",
    origin: "South Africa",
    generation: "Genus: Aloe, Family: Asphodelaceae",
    description:
      "Aloe aristata, also known as Lace Aloe, is renowned for its attractive rosette of small, spiky leaves adorned with white, lacy teeth. It is a hardy succulent that thrives in bright indirect light and requires moderate watering. Its unique leaf texture makes it a striking addition to any plant collection.",
    image: ["./img/13.png", "./img/14.png", "./img/15.png"],
    price: "1700",
  },
  {
    id: 156,
    name: "Aloe juvenna",
    species: "Aloe juvenna",
    type: "Succulent",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Tanzania",
    generation: "Genus: Aloe, Family: Asphodelaceae",
    description:
      "Aloe juvenna, commonly known as Tiger Tooth Aloe, features compact rosettes of triangular, spiky leaves with distinctive white teeth along the edges. It is well-suited for bright indirect light and requires moderate watering. This plant’s striking leaf structure makes it a popular choice for succulent arrangements.",
    image: ["./img/16.png", "./img/17.png", "./img/18.png"],
    price: "4900",
  },
  {
    id: 157,
    name: "Aloe ferox",
    species: "Aloe ferox",
    type: "Succulent",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Full Sun to Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Slow to Moderate",
    origin: "South Africa",
    generation: "Genus: Aloe, Family: Asphodelaceae",
    description:
      "Aloe ferox, commonly known as Cape Aloe, is a robust succulent with tall, spiky leaves that can form dense rosettes. The plant is renowned for its striking appearance and medicinal properties. It thrives in full sun to bright indirect light and prefers moderate watering. Its leaf margins have reddish spines, adding to its visual appeal.",
    image: ["./img/19.png", "./img/20.png", "./img/21.png"],
    price: "2500",
  },
  {
    id: 158,
    name: "Aloe striata",
    species: "Aloe striata",
    type: "Succulent",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Slow",
    origin: "South Africa",
    generation: "Genus: Aloe, Family: Asphodelaceae",
    description:
      "Aloe striata, commonly known as Coral Aloe, is distinguished by its smooth, coral-pink to light green leaves that form a rosette. This succulent is well-suited to bright indirect light and moderate watering. Its attractive foliage and compact growth make it a lovely addition to any succulent collection.",
    image: ["./img/22.png", "./img/23.png", "./img/24.png"],
    price: "2900",
  },
  {
    id: 159,
    name: "Aloe hereroensis",
    species: "Aloe hereroensis",
    type: "Succulent",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Bright Indirect Light",
    water: "Low to Moderate",
    soil: "Well-draining",
    growthRate: "Slow",
    origin: "Namibia",
    generation: "Genus: Aloe, Family: Asphodelaceae",
    description:
      "Aloe hereroensis, also known as Herero Aloe, features a rosette of narrow, elongated leaves with distinctive white spots and margins. It is well-adapted to bright indirect light and has low to moderate water needs. Its unique leaf pattern and slow growth make it an attractive choice for succulent enthusiasts.",
    image: ["./img/25.png", "./img/26.png", "./img/27.png"],
    price: "3100",
  },
  {
    id: 160,
    name: "Opuntia ficus-indica",
    species: "Opuntia ficus-indica",
    type: "Cactus",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Full Sun",
    water: "Low",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Mexico",
    generation: "Genus: Opuntia, Family: Cactaceae",
    description:
      "Opuntia ficus-indica, commonly known as Prickly Pear Cactus, is a large, flat-cactus with broad, pad-like segments covered in spines. It thrives in full sun and requires minimal water. The plant produces edible fruit called prickly pears and is valued for its ornamental and culinary uses.",
    image: ["./img/28.png", "./img/29.png", "./img/30.png"],
    price: "6000",
  },
  {
    id: 161,
    name: "Opuntia dillenii",
    species: "Opuntia dillenii",
    type: "Cactus",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Full Sun",
    water: "Low",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Southern United States, Mexico",
    generation: "Genus: Opuntia, Family: Cactaceae",
    description:
      "Opuntia dillenii, also known as Common Prickly Pear, is characterized by its flat, pad-like segments covered in spines and clusters of small, yellow flowers. It thrives in full sun and requires minimal water. This cactus is valued for its resilience and its vibrant fruit, which can be used in culinary applications.",
    image: ["./img/31.png", "./img/32.png", "./img/33.png"],
    price: "5230",
  },
  {
    id: 162,
    name: "Opuntia humifusa",
    species: "Opuntia humifusa",
    type: "Cactus",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Full Sun",
    water: "Low",
    soil: "Well-draining",
    growthRate: "Slow to Moderate",
    origin: "Eastern United States",
    generation: "Genus: Opuntia, Family: Cactaceae",
    description:
      "Opuntia humifusa, known as Eastern Prickly Pear, is a hardy cactus with flat, rounded pads and bright yellow or red flowers. It is well-suited for full sun and dry conditions, making it ideal for low-maintenance gardens. This species produces edible, tangy fruit and is valued for its decorative and practical uses.",
    image: ["./img/34.png", "./img/35.png", "./img/36.png"],
    price: "4290",
  },
  {
    id: 163,
    name: "Opuntia microdasys",
    species: "Opuntia microdasys",
    type: "Cactus",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Full Sun",
    water: "Low",
    soil: "Well-draining",
    growthRate: "Slow to Moderate",
    origin: "Mexico",
    generation: "Genus: Opuntia, Family: Cactaceae",
    description:
      "Opuntia microdasys, commonly known as Bunny Ear Cactus, features small, round pads covered in tiny, hair-like spines that resemble bunny ears. It thrives in full sun and requires minimal water. This cactus is popular for its unique appearance and is often used as a decorative plant in xeriscapes and indoor gardens.",
    image: ["./img/37.png", "./img/38.png", "./img/39.png"],
    price: "2500",
  },
  {
    id: 164,
    name: "Opuntia rufida",
    species: "Opuntia rufida",
    type: "Cactus",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Full Sun",
    water: "Low",
    soil: "Well-draining",
    growthRate: "Moderate",
    origin: "Mexico",
    generation: "Genus: Opuntia, Family: Cactaceae",
    description:
      "Opuntia rufida, or Rufous Prickly Pear, is noted for its reddish-brown to purplish pads and vibrant yellow flowers. It is a resilient cactus that thrives in full sun and well-draining soil. This species is valued for its striking appearance and is often used as an ornamental plant in gardens and landscapes.",
    image: ["./img/40.png", "./img/41.png", "./img/42.png"],
    price: "2300",
  },
  {
    id: 165,
    name: "Crassula ovata",
    species: "Crassula ovata",
    type: "Succulent",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Bright Indirect Light",
    water: "Low",
    soil: "Well-draining",
    growthRate: "Slow to Moderate",
    origin: "South Africa",
    generation: "Genus: Crassula, Family: Crassulaceae",
    description:
      "Crassula ovata, commonly known as the Jade Plant, features thick, glossy, oval-shaped leaves and a tree-like growth habit. It is prized for its easy care and longevity, making it a popular choice for indoor plants. The Jade Plant thrives in bright, indirect light and requires minimal watering, adapting well to various indoor conditions.",
    image: ["./img/43.png", "./img/44.png", "./img/45.png"],
    price: "2900",
  },
  {
    id: 166,
    name: "Crassula perforata",
    species: "Crassula perforata",
    type: "Succulent",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Bright Indirect Light",
    water: "Low",
    soil: "Well-draining",
    growthRate: "Slow to Moderate",
    origin: "South Africa",
    generation: "Genus: Crassula, Family: Crassulaceae",
    description:
      "Crassula perforata, commonly known as String of Buttons, is recognized for its unique, stacked, button-like leaves that create a cascading effect. This succulent is well-suited for hanging baskets or as a trailing plant in containers. It prefers bright, indirect light and requires infrequent watering, making it an ideal choice for low-maintenance indoor gardens.",
    image: ["./img/46.png", "./img/47.png", "./img/48.png"],
    price: "2100",
  },
  {
    id: 167,
    name: "Crassula arborescens",
    species: "Crassula arborescens",
    type: "Succulent",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Bright Indirect Light",
    water: "Low",
    soil: "Well-draining",
    growthRate: "Slow to Moderate",
    origin: "South Africa",
    generation: "Genus: Crassula, Family: Crassulaceae",
    description:
      "Crassula arborescens, commonly known as the Silver Dollar Plant, is admired for its rounded, silver-gray leaves that give it a distinctive appearance. This succulent has a bushy, tree-like growth habit and is often used as a decorative indoor plant. It thrives in bright, indirect light and requires minimal watering, making it a resilient and low-maintenance choice for indoor gardens.",
    image: ["./img/49.png", "./img/50.png", "./img/51.png"],
    price: "2100",
  },
  {
    id: 168,
    name: "Crassula tetragona",
    species: "Crassula tetragona",
    type: "Succulent",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Bright Indirect Light",
    water: "Low",
    soil: "Well-draining",
    growthRate: "Slow",
    origin: "South Africa",
    generation: "Genus: Crassula, Family: Crassulaceae",
    description:
      "Crassula tetragona, also known as Miniature Pine Tree, features small, needle-like leaves that give it a pine tree-like appearance. This succulent has an upright growth habit, resembling a miniature conifer, and is ideal for adding a unique touch to indoor plant collections. It prefers bright, indirect light and requires minimal watering, thriving in well-draining soil.",
    image: ["./img/52.png", "./img/53.png", "./img/54.png"],
    price: "2900",
  },
  {
    id: 169,
    name: "Crassula falcata",
    species: "Crassula falcata",
    type: "Succulent",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Bright Indirect Light",
    water: "Low",
    soil: "Well-draining",
    growthRate: "Slow to Moderate",
    origin: "South Africa",
    generation: "Genus: Crassula, Family: Crassulaceae",
    description:
      "Crassula falcata, commonly known as Propeller Plant, is renowned for its distinctive, fan-shaped leaves that resemble propeller blades. This succulent has a rosette growth form and features gray-green leaves with red margins. It thrives in bright, indirect light and requires infrequent watering, making it a resilient choice for indoor gardens.",
    image: ["./img/55.png", "./img/56.png", "./img/57.png"],
    price: "2600",
  },
  {
    id: 200,
    name: "Senecio rowleyanus",
    species: "Senecio rowleyanus",
    type: "Succulent",
    category: "Ornamental",
    main: "SucculentsData",
    sunlight: "Bright Indirect Light",
    water: "Moderate",
    soil: "Well-draining",
    growthRate: "Slow",
    origin: "South Africa",
    generation: "Genus: Senecio, Family: Asteraceae",
    description:
      "Senecio rowleyanus, commonly known as String of Pearls, features unique, bead-like leaves that resemble pearls strung along thin, trailing stems. It’s a popular choice for hanging baskets or pots, needing bright indirect light and minimal watering.",
    image: ["./img/148.png", "./img/149.png", "./img/150.png"],
    price: "2900",
  },
  // Flowering shrubs
  {
    id: 201,
    name: "Rosa damascena",
    species: "Rosa damascena",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining, Fertile",
    growthRate: "Moderate",
    origin: "Middle East",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "Rosa damascena, or Damask Rose, is renowned for its fragrant, pink to red blooms and its use in perfumes and essential oils. This rose variety thrives in full sun and well-draining soil, requiring moderate watering. It is cherished for its classic, old-fashioned fragrance and appearance.",
    image: ["./img/151.png", "./img/152.png", "./img/153.png"],
    price: "540",
  },
  {
    id: 202,
    name: "Rosa centifolia",
    species: "Rosa centifolia",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining, Fertile",
    growthRate: "Slow to Moderate",
    origin: "Middle East",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "Rosa centifolia, also known as Cabbage Rose, is famous for its large, full, and highly fragrant blooms that resemble a cabbage. It is valued for its use in perfumes and its beautiful appearance. This rose variety prefers full sun and well-draining soil, with moderate watering requirements.",
    image: ["./img/154.png", "./img/155.png", "./img/156.png"],
    price: "490",
  },
  {
    id: 203,
    name: "Rosa chinensis",
    species: "Rosa chinensis",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun to Partial Shade",
    water: "Moderate",
    soil: "Well-draining, Fertile",
    growthRate: "Moderate",
    origin: "China",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "Rosa chinensis, commonly known as China Rose, is appreciated for its abundant blooms and versatility. It produces elegant, fragrant flowers that vary in color from pink to red. The plant thrives in full sun to partial shade and prefers well-draining, fertile soil.",
    image: ["./img/157.png", "./img/158.png", "./img/159.png"],
    price: "500",
  },
  {
    id: 204,
    name: "Rosa gallica",
    species: "Rosa gallica",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun to Partial Shade",
    water: "Moderate",
    soil: "Well-draining, Fertile",
    growthRate: "Slow to Moderate",
    origin: "Europe",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "Rosa gallica, or Gallica Rose, is known for its historical significance and fragrant, richly colored blooms. This rose species produces deep red to pink flowers and is valued for its hardy nature. It thrives in full sun to partial shade and requires well-draining, fertile soil.",
    image: ["./img/160.png", "./img/161.png", "./img/162.png"],
    price: "590",
  },
  {
    id: 205,
    name: "Rosa rugosa",
    species: "Rosa rugosa",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun to Partial Shade",
    water: "Low to Moderate",
    soil: "Well-draining, Sandy",
    growthRate: "Fast",
    origin: "East Asia",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "Rosa rugosa, or Rugosa Rose, is known for its fragrant, wrinkled leaves and large, colorful blooms. This resilient rose species is particularly valued for its ability to thrive in various soil types and its resistance to disease. It produces vibrant flowers in shades of pink, red, or white and is often used in hedges and coastal gardens.",
    image: ["./img/163.png", "./img/164.png", "./img/165.png"],
    price: "420",
  },
  {
    id: 206,
    name: "Rosa alba",
    species: "Rosa alba",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun to Partial Shade",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Slow to Moderate",
    origin: "Europe",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "Rosa alba, commonly known as Alba Rose, is cherished for its classic, elegant white blooms and fragrant foliage. It is a hardy rose that can tolerate a range of soil types and environmental conditions. The Alba Rose is often used in traditional and historical gardens for its timeless beauty and fragrance.",
    image: ["./img/166.png", "./img/167.png", "./img/168.png"],
    price: "570",
  },
  {
    id: 207,
    name: "Rosa bengalensis",
    species: "Rosa bengalensis",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun to Partial Shade",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate",
    origin: "India and Southeast Asia",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "Rosa bengalensis, or Bengal Rose, is known for its vibrant and striking blooms that can range from pink to deep red. This rose is native to India and Southeast Asia, where it thrives in warm climates. It is valued for its rich color and robustness, making it a popular choice for gardens and landscaping.",
    image: ["./img/169.png", "./img/170.png", "./img/171.png"],
    price: "700",
  },
  {
    id: 208,
    name: "Rosa indica",
    species: "Rosa indica",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun to Partial Shade",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate",
    origin: "India and Southeast Asia",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "Rosa indica, commonly known as Indian Rose, is admired for its beautiful and fragrant flowers. Native to India and Southeast Asia, this rose variety is well-suited to warm climates. It features a range of colors from soft pink to vibrant red and is popular in gardens for its ornamental value.",
    image: ["./img/172.png", "./img/173.png", "./img/174.png"],
    price: "300",
  },
  {
    id: 209,
    name: "Rosa multiflora",
    species: "Rosa multiflora",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun to Partial Shade",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Fast",
    origin: "East Asia",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "Rosa multiflora, commonly known as Multiflora Rose, is known for its abundant clusters of small, fragrant flowers. Native to East Asia, this rose variety is fast-growing and is often used as a ground cover or climbing rose. It produces a profusion of blooms in various shades, including white, pink, and red.",
    image: ["./img/175.png", "./img/176.png", "./img/177.png"],
    price: "400",
  },
  {
    id: 210,
    name: "Rosa muscosa",
    species: "Rosa muscosa",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate",
    origin: "Europe",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "Rosa muscosa, commonly known as Moss Rose, is recognized for its unique, moss-like foliage and fragrant flowers. This rose species produces large, attractive blooms with a distinctive, velvety texture on the buds. It thrives in full sun and well-draining soil, making it a popular choice for ornamental gardens.",
    image: ["./img/178.png", "./img/179.png", "./img/180.png"],
    price: "530",
  },
  {
    id: 211,
    name: "Rosa Hybrid Tea",
    species: "Rosa hybrid",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate to Fast",
    origin: "Hybrid",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "The Hybrid Tea Rose is a popular and elegant rose variety known for its large, high-centered blooms and long stems. It’s prized for its wide range of colors and classic rose fragrance. These roses prefer full sun and well-draining soil, and they can be grown in various climates.",
    image: ["./img/181.png", "./img/182.png", "./img/183.png"],
    price: "490",
  },
  {
    id: 212,
    name: "Rosa Floribunda",
    species: "Rosa hybrid",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate to Fast",
    origin: "Hybrid",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "The Floribunda Rose is known for its abundant clusters of flowers that bloom profusely throughout the growing season. It combines the traits of Hybrid Tea and Polyantha roses, resulting in a variety with compact growth and a wide range of colors. Floribunda Roses are valued for their continuous blooming and resilience.",
    image: ["./img/184.png", "./img/185.png", "./img/186.png"],
    price: "490",
  },
  {
    id: 213,
    name: "Rosa Grandiflora",
    species: "Rosa hybrid",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate to Fast",
    origin: "Hybrid",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "The Grandiflora Rose is a hybrid that combines the traits of Hybrid Tea and Floribunda roses. It is known for its large, elegant blooms and strong growth. Grandiflora Roses typically produce a few large flowers per stem, and they are celebrated for their beauty and the long-lasting nature of their blooms.",
    image: ["./img/187.png", "./img/188.png", "./img/189.png"],
    price: "600",
  },
  {
    id: 214,
    name: "Rosa Climbing",
    species: "Rosa hybrid",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun to Partial Shade",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Fast",
    origin: "Hybrid",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "Climbing Roses are known for their vigorous growth and ability to cover trellises, walls, and arbors with their beautiful blooms. They produce clusters of flowers and can be trained to grow vertically, making them ideal for creating stunning vertical gardens. The blooms can vary in color and fragrance, and they require regular pruning to maintain their shape and encourage blooming.",
    image: ["./img/190.png", "./img/191.png", "./img/192.png"],
    price: "390",
  },
  {
    id: 215,
    name: "Rosa Miniature",
    species: "Rosa hybrid",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun to Partial Shade",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Slow to Moderate",
    origin: "Hybrid",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "Miniature Roses are known for their small size and delicate blooms, making them perfect for containers, small gardens, or as indoor plants. They have a compact growth habit and produce flowers in a range of colors and fragrances. Despite their small size, they require similar care to full-sized roses, including regular watering, feeding, and pruning to keep them healthy and blooming.",
    image: ["./img/193.png", "./img/194.png", "./img/195.png"],
    price: "490",
  },
  {
    id: 216,
    name: "Rosa Shrub",
    species: "Rosa hybrid",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate to Fast",
    origin: "Hybrid",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "Shrub Roses are known for their robust and bushy growth, making them excellent for hedges and garden borders. They produce a profusion of blooms throughout the growing season and are valued for their ability to withstand a range of growing conditions. These roses require regular pruning to maintain shape and encourage new growth.",
    image: ["./img/196.png", "./img/197.png", "./img/198.png"],
    price: "490",
  },
  {
    id: 217,
    name: "Rosa Hybrid Musk",
    species: "Rosa hybrid",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun to Partial Shade",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate",
    origin: "Hybrid",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "The Hybrid Musk Rose is known for its fragrant, clustered blooms and vigorous growth. It produces a continuous display of flowers in a range of colors, often with a musky scent. This variety is appreciated for its resilience and ability to thrive in various climates, making it a popular choice for garden landscapes.",
    image: ["./img/199.png", "./img/200.png", "./img/201.png"],
    price: "610",
  },
  {
    id: 218,
    name: "Rosa Teas",
    species: "Rosa hybrid",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate",
    origin: "Hybrid",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "The Tea Rose is renowned for its large, fragrant blooms and elegant form. It produces flowers in a variety of colors and has a delightful scent, often used in perfumes. Tea Roses are known for their classic beauty and are a popular choice for formal gardens and floral arrangements.",
    image: ["./img/202.png", "./img/idk.png", "./img/203.png"],
    price: "500",
  },
  {
    id: 219,
    name: "Rosa Portland",
    species: "Rosa hybrid",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun to Partial Shade",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Slow to Moderate",
    origin: "Hybrid",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "The Portland Rose is a classic rose variety known for its rich, deep colors and strong fragrance. It features sturdy, upright growth and is often used in formal gardens and landscapes. This rose is named after the Portland family, who were prominent rose breeders.",
    image: ["./img/204.png", "./img/205.png", "./img/206.png"],
    price: "420",
  },
  {
    id: 250,
    name: "Rosa Pat Austin",
    species: "Rosa hybrid",
    type: "Flowering Plant",
    category: "Ornamental",
    main: "FloweringData",
    sunlight: "Full Sun",
    water: "Moderate",
    soil: "Well-draining, Loamy",
    growthRate: "Moderate",
    origin: "United Kingdom",
    generation: "Genus: Rosa, Family: Rosaceae",
    description:
      "Rosa Pat Austin is renowned for its rich, warm apricot blooms that fade to a soft gold. This variety is known for its strong fragrance and repeat flowering throughout the growing season. It has a robust growth habit and is ideal for both formal and informal garden settings.",
    image: ["./img/294.png", "./img/295.png", "./img/296.png"],
    price: "490",
  },
];
